server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/payCloudDb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# 消费者将要去访问的微服务名称（注册进nacos的微服务提供者）
server-url:
  nacos-user-service: http://nacos-payment-provider