server:
  port: 3344
  tomcat:
    max-http-form-post-size: 8192

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yxj-yp/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
      label: master
# rabbitmq 配置
rabbitmq:
  host: localhsot
  prot: 5762
  username: guest
  passward: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
# 暴露监控端点
management:
  endpoint:
    web:
      exposure:
        include: 'bus-refresh'