server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/payCloudDb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)ribbon jar冲突
#ribbon:
#  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  # 指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000

feign:
  client:
    config:
      default:
        #简历连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 10000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.yy.springcloud.service.PaymentFeignService: debug

